root_dir: ${oc.env:PROJECT_ROOT}

input_image_dir: ${paths.root_dir}/inputs/images

input_video_dir: ${paths.root_dir}/inputs/videos

output_image_dir: ${paths.root_dir}/outputs/images

output_video_dir: ${paths.root_dir}/outputs/videos

filters_dir: ${paths.input_image_dir}/filters

input_csv_dir: ${paths.root_dir}/inputs/csv_files

pretrained_weight_dir: ${paths.root_dir}/inputs/pretrained_weights